name: Run piha everyday at 10 AM IST

on:
  schedule:
    - cron: "30 4 * * *" # 10 AM IST

jobs:
  piha-runner:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          go get -v -t -d ./...

      - name: Run piha
        run: |
          go run piha.go
        env:
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_KEY_SECRET: ${{ secrets.TWITTER_API_KEY_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
